### ISSUE TITLE
Home - Página principal

### ISSUE THREAD

**Issue by GeraYF** [GeraYF/Proyect-Programaci-n#3]
Presenta una vista general de productos destacados, ofertas y categorías principales.

![Image](https://github.com/user-attachments/assets/cd004781-7900-4423-af2a-42457eccf089)

![Image](https://github.com/user-attachments/assets/67fb7c18-6334-41e7-8fad-424515799011)

**Comment by Ghostcito** [comment]
Tarea parcialmente terminada
